name: Deploy on Docker Hub

on:
  push:
    branches:
      - develop

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-disabled: true

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and tag Docker image
        run: |
          cd customer-service
          ./gradlew clean build -x test
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/customer-service:${{ github.sha }} .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/customer-service:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/customer-service:latest

      - name: Push Docker image to DockerHub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/customer-service:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/customer-service:latest
